# Configuration for LLM Judge Pipeline

# Sampling configuration
sample:
  input: "preprocessed_data/preprocessed_data.csv"
  output: "preprocessed_data/sample_500.csv"
  random_seed: 42
  n: 500

# Multi-judge configuration (used by main.py and run_multi_judge.py)
multi_judge:
  input: "preprocessed_data/sample_500.csv"
  system_prompt: "prompts/llmaj_prompt_by_grazie"
  results_dir: "results"
  models:
#    - "groq:openai/gpt-oss-120b"

    - "cerebras:gpt-oss-120b"
    - "cerebras:qwen-3-235b-a22b-instruct-2507"
#
#    - "openrouter:gpt-oss-120b:free"
#    - "openrouter:qwen/qwen3-235b-a22b-2507"
#    - "openrouter:deepseek/deepseek-v3.2"

#    - "huggingface:openai/gpt-oss-120b:novita"
#    - "huggingface:Qwen/Qwen3-235B-A22B-Instruct-2507:together"
#    - "huggingface:deepseek-ai/DeepSeek-V3.2:novita"
