import pandas as pd
from tqdm.auto import tqdm
from pydantic import BaseModel, Field
from typing import Literal
from src.lang_ai.core.logger import setup_logging

logger = setup_logging()


class PollutionFilter(BaseModel):
    """
    A configurable filter for removing polluted posts from a DataFrame.
    """

    filter_patterns: dict[str, str] = {
        "bot": (
            r"(?i)("
            r"I am a bot|"
            r"contact the moderators of this subreddit|"
            r"message (the|this) mod|"
            r"questions or concerns\.|"
            r"This message was (generated|posted) automatically|"
            r"\[(deleted|removed)\]"
            r")"
        ),
        "ad": (
            r"(?i)("
            r"link in (bio|profile|comments)|"
            r"check out my (channel|stream|store|patreon|youtube)|"
            r"limited time offer|"
            r"discount code|"
            r"free shipping|"
            r"get yours (here|now)|"
            r"use code [A-Z0-9]+|"
            r"(buy|purchase) now|"
            r"official store"
            r")"
        ),
        "ai": (
            r"(?i)("
            r"As an AI language model|"
            r"As a large language model|"
            r"I am (?:an|a) (?:AI|artificial intelligence|computer program|machine learning model)|"
            r"I do not have (?:personal opinions|beliefs|feelings|consciousness)|"
            r"My knowledge cutoff|"
            r"I cannot (?:browse|access) (?:the internet|real-time information)|"
            r"generated by (?:an AI|ChatGPT|Claude|Gemini|LLM)"
            r")"
        ),
    }
    text_column: str = Field(
        default="post", description="Name of the column containing text to filter"
    )

    def filter_by_pattern(
        self,
        df: pd.DataFrame,
        pattern_name: str,
    ) -> pd.DataFrame:
        """
        Filters out rows where the text column matches a specific regex pattern.

        Args:
            df (pd.DataFrame): The input DataFrame containing posts.
            pattern_name (str): The name of the pattern to filter by (e.g., 'bot', 'ad', 'ai').

        Returns:
            pd.DataFrame: The DataFrame with matching rows removed.

        Raises:
            KeyError: If the specified pattern_name is not found in filter_patterns.
        """
        logger.info(f"Filtering by pattern: {pattern_name}")
        if pattern_name not in self.filter_patterns:
            raise KeyError(f"Pattern '{pattern_name}' not found in filter_patterns")

        pattern = self.filter_patterns[pattern_name]
        df_clean = df[~df[self.text_column].str.contains(pattern, regex=True, na=False)]
        logger.info(
            f"Removed {df.shape[0] - df_clean.shape[0]} rows matching pattern '{pattern_name}'"
        )
        return df_clean

    def filter_by_patterns(
        self,
        df: pd.DataFrame,
        pattern_names: list[str] | Literal["all"],
    ) -> pd.DataFrame:
        """
        Filters out rows matching multiple regex patterns.

        Args:
            df (pd.DataFrame): The input DataFrame containing posts.
            pattern_names (list[str] | Literal["all"]): A list of pattern names to filter by,
                or "all" to apply all available patterns.

        Returns:
            pd.DataFrame: The DataFrame with all matching rows removed.
        """
        if pattern_names == "all":
            pattern_names = list(self.filter_patterns.keys())
        logger.info(f"Filtering by patterns: {pattern_names}")
        for pattern_name in tqdm(pattern_names, desc="Filtering pollution"):
            df = self.filter_by_pattern(df, pattern_name)
        logger.info(f"Removed {df.shape[0]} rows matching all patterns")
        return df
