"""
Filters for identifying and removing undesirable content (bots, ads, AI-generated) from data.
"""

from typing import Dict, List, Optional

import pandas as pd

from src.lang_ai.data.base_filter import TextFilter


class PollutionFilter(TextFilter):
    """
    Filter for removing polluted posts (bots, ads, AI-generated content).

    Inherits from TextFilter and removes entire rows containing pollution patterns.
    """

    def get_filter_patterns(self) -> Dict[str, str]:
        """
        Return pre-built regex patterns for pollution detection.

        Returns:
            Dictionary mapping category to regex pattern
        """
        return {
            "bot": (
                r"(?i)(?:"
                r"I am a bot|"
                r"contact the moderators of this subreddit|"
                r"message (the|this) mod|"
                r"questions or concerns\.|"
                r"This message was (generated|posted) automatically|"
                r"\[(deleted|removed)\]"
                r")"
            ),
            "ad": (
                r"(?i)(?:"
                r"link in (bio|profile|comments)|"
                r"check out my (channel|stream|store|patreon|youtube)|"
                r"limited time offer|"
                r"discount code|"
                r"free shipping|"
                r"get yours (here|now)|"
                r"use code [A-Z0-9]+|"
                r"(buy|purchase) now|"
                r"official store"
                r")"
            ),
            "ai": (
                r"(?i)(?:"
                r"As an AI language model|"
                r"As a large language model|"
                r"I am (?:an|a) (?:AI|artificial intelligence|computer program|machine learning model)|"
                r"I do not have (?:personal opinions|beliefs|feelings|consciousness)|"
                r"My knowledge cutoff|"
                r"I cannot (?:browse|access) (?:the internet|real-time information)|"
                r"generated by (?:an AI|ChatGPT|Claude|Gemini|LLM)"
                r")"
            ),
        }

    def get_replacement_token(self, category: str) -> Optional[str]:
        """
        Return None to remove rows instead of replacing text.

        Args:
            category: The pollution category

        Returns:
            None (rows will be removed)
        """
        return None

    def get_category_label(self, category: str) -> str:
        """
        Get human-readable labels for pollution categories.

        Args:
            category: The category name

        Returns:
            Human-readable label
        """
        labels = {
            "bot": "Bot Messages",
            "ad": "Advertisements",
            "ai": "AI-Generated Content",
        }
        return labels.get(category, category.title())

    def filter_by_patterns(
        self,
        df: pd.DataFrame,
        pattern_names: List[str] | str,
    ) -> pd.DataFrame:
        """
        Legacy method for backward compatibility.

        Use apply_filter() or apply_all() instead.
        """
        df_filtered, _ = self.apply_filter(df, pattern_names)
        return df_filtered
